apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    name: frontend
  namespace: batch29
spec:
  containers:
  - name: myfirstpodcontainer
    image: psrv3/devopsbatch29
    ports:
    - containerPort: 5000
